
spring:
  profiles:
    active: dev # 环境切换
  application:
    name: auth-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
 # 日志
logging:
  config: classpath:log4j2.yml
  level:
     org.springframework: debug

management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3


# mybatis配置
mybatis:
  ## 实体类路径
  typeAliasesPackage: com.ziyun.auth.model
  ## mapping文件路径
  mapperLocations: classpath:mapper/*.xml
  ## 配置文件路径
  configLocation: classpath:mybatis-config.xml

# mapper插件配置
mapper:
    mappers: com.ziyun.auth.util.ZyMapper
    not-empty: false
    identity: MYSQL

# 分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
---

# 测试环境
server:
  port: 7012
  max-http-header-size: 40960
spring:
  profiles: test
  datasource:
    name: test
    url: jdbc:mysql://192.168.101.218:3306/datacenter_v2?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: dev
    password: Y31uJJgtiJSyUD2n
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    ## Redis数据库索引（默认为0）
    database: 1
    ## 主机
    host: 192.168.101.212
    ## 端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: NaRT9gnxMKZ6MqA2
    ## 连接超时时间（毫秒）
    timeout: 100000
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 600
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      ## 连接池中的最大空闲连接
      max-idle: 300
      ## 连接池中的最小空闲连接
      min-idle: 200
# eureka server
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.101.211:8606/eureka/
  instance:
      ## 租期更新时间间隔（默认30秒）
      leaseRenewalIntervalInSeconds: 15
      ## 租期到期时间（默认90秒）
      leaseExpirationDurationInSeconds: 30

ribbon:
   eureka:
     enabled: true
   ReadTimeout: 60000
   ConnectTimeout: 60000

# swagger 配置
swagger:
 show: true
auth:
   accessToken:
     url: http://localhost:${server.port}/oauth/token
---

# 开发环境
server:
  port: 7012
  max-http-header-size: 102400
spring:
  profiles: dev
  datasource:
    name: test
    url: jdbc:mysql://192.168.101.218:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: dev
    password: Y31uJJgtiJSyUD2n
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## 主机
    host: 192.168.101.212
    ## 端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: NaRT9gnxMKZ6MqA2
    ## 连接超时时间（毫秒）
    timeout: 100000
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 600
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      ## 连接池中的最大空闲连接
      max-idle: 300
      ## 连接池中的最小空闲连接
      min-idle: 200
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8606/eureka/
    instance:
          ## 租期更新时间间隔（默认30秒）
          leaseRenewalIntervalInSeconds: 15
          ## 租期到期时间（默认90秒）
          leaseExpirationDurationInSeconds: 30
ribbon:
   eureka:
     enabled: true
   ReadTimeout: 60000
   ConnectTimeout: 60000

# swagger 配置
swagger:
 show: true

#获取access_token的url
auth:
   accessToken:
     url: http://localhost:${server.port}/oauth/token
---

# 生产环境
server:
  port: 7012
  max-http-header-size: 40960
spring:
  profiles: prod
  datasource:
    name: test
    url: jdbc:mysql://10.130.254.28:3306/datacenter?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dd@2018
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## 主机
    host: 10.130.254.28
    ## 端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    ## 连接超时时间（毫秒）
    timeout: 100000
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 600
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      ## 连接池中的最大空闲连接
      max-idle: 300
      ## 连接池中的最小空闲连接
      min-idle: 200
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://10.130.254.28:8606/eureka/
    instance:
              ## 租期更新时间间隔（默认30秒）
              leaseRenewalIntervalInSeconds: 15
              ## 租期到期时间（默认90秒）
              leaseExpirationDurationInSeconds: 30
ribbon:
   eureka:
     enabled: true
   ReadTimeout: 60000
   ConnectTimeout: 60000
# swagger 配置
swagger:
 show: false
