spring:
  ## 环境切换
  profiles:
    active: test
  application:
    name: chart-service
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

# mybatis配置
mybatis:
  ## 实体类路径
  typeAliasesPackage: com.ziyun.chart.entity
  ## mapping文件路径
  mapperLocations: classpath:mapping/*.xml

# mapper插件配置
mapper:
    mappers: com.ziyun.chart.util.ZyMapper
    not-empty: false
    identity: MYSQL

 # 日志配置
logging:
  config: classpath:log4j2.yml
---

# 开发环境
server:
  port: 7020
  max-http-header-size: 40960
spring:
  profiles: dev
  datasource:
      name: mysqlDataSource
      url: jdbc:mysql://192.168.101.217:3306/datacenter_dev_v2?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: dev
      password: lJZx2Ik5eqX3xBDp
      driver-class-name: com.mysql.jdbc.Driver
      testOnBorrow: true
      validationQuery: select 1
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## 主机
    host: 192.168.101.212
    ## 端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    ## 连接超时时间（秒）
    timeout: 43200
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 600
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      ## 连接池中的最大空闲连接
      max-idle: 300
      ## 连接池中的最小空闲连接
      min-idle: 200
# eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8606/eureka/
  instance:
    ## 租期更新时间间隔（默认30秒）
    leaseRenewalIntervalInSeconds: 15
    ## 租期到期时间（默认90秒）
    leaseExpirationDurationInSeconds: 30

authority:
    management:
        path: http://192.168.101.211:8101
# swagger 配置
swagger:
 show: true

ribbon:
   eureka:
     enabled: true
   ReadTimeout: 60000
   ConnectTimeout: 60000

---

 #测试环境
spring:
  profiles: test
  datasource:
        name: mysqlDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.101.218:3306/datacenter_v2?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: app
        password: ZFRwjk2RPNxD346z
        testOnBorrow: true
        validationQuery: select 1
  redis:
    ## Redis数据库索引（默认为0）
    database: 1
    ## 主机
    host: 192.168.101.212
    ## 端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    ## 连接超时时间（秒）
    timeout: 43200
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 600
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      ## 连接池中的最大空闲连接
      max-idle: 300
      ## 连接池中的最小空闲连接
      min-idle: 200

server:
  port: 7020
  max-http-header-size: 40960

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.101.211:8606/eureka/
  instance:
    ## 租期更新时间间隔（默认30秒）
    leaseRenewalIntervalInSeconds: 15
    ## 租期到期时间（默认90秒）
    leaseExpirationDurationInSeconds: 30
# swagger 配置
swagger:
 show: true
authority:
    management:
        path: http://192.168.101.211:8101
ribbon:
   eureka:
     enabled: true
---

# 生产环境
server:
  port: 7020
  max-http-header-size: 40960
spring:
  profiles: prod
  datasource:
       name: mysqlDataSource
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.130.254.28:3306/datacenter?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
       username: root
       password: dd@2018
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## 主机
    host: 10.130.254.28
    ## 端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    ## 连接超时时间（秒）
    timeout: 43200
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 600
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      ## 连接池中的最大空闲连接
      max-idle: 300
      ## 连接池中的最小空闲连接
      min-idle: 200
# eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.130.254.28:8606/eureka/
  instance:
    ## 租期更新时间间隔（默认30秒）
    leaseRenewalIntervalInSeconds: 15
    ## 租期到期时间（默认90秒）
    leaseExpirationDurationInSeconds: 30


# swagger 配置
swagger:
 show: false

ribbon:
   eureka:
     enabled: true
